name: Repo -> S3
on:
  push:
    branches:
    - '**'
jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: S3 Backup
        uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          MIRROR_TARGET: ${{ secrets.S3_MIRROR_TARGET }}
          SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          STORAGE_SERVICE_URL:  ${{ secrets.S3_URL }}
        with:
          args: --overwrite --remove
